"""Add manager applications table

Revision ID: 3a5addc8fb64
Revises: e681f1ada7ff
Create Date: 2022-04-29 00:15:21.007945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5addc8fb64'
down_revision = 'e681f1ada7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managementApplications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managementApplications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managementApplications_answered'), ['answered'], unique=False)
        batch_op.create_index(batch_op.f('ix_managementApplications_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managementApplications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managementApplications_id'))
        batch_op.drop_index(batch_op.f('ix_managementApplications_answered'))

    op.drop_table('managementApplications')
    # ### end Alembic commands ###
