"""Add more fields to videos

Revision ID: 7017c444fbd1
Revises: ef2d21aeab9a
Create Date: 2022-05-15 00:33:35.833500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7017c444fbd1'
down_revision = 'ef2d21aeab9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resource_link', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('thumbnail_image_link', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_image_link')
        batch_op.drop_column('resource_link')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
