"""Add reported videos table

Revision ID: bb6304951fcb
Revises: 32a00d832914
Create Date: 2022-05-21 15:43:22.902249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6304951fcb'
down_revision = '32a00d832914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportedVideos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reportedVideos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reportedVideos_answered'), ['answered'], unique=False)
        batch_op.create_index(batch_op.f('ix_reportedVideos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportedVideos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reportedVideos_id'))
        batch_op.drop_index(batch_op.f('ix_reportedVideos_answered'))

    op.drop_table('reportedVideos')
    # ### end Alembic commands ###
